### ISSUE TITLE
Outdated README instructions

### ISSUE THREAD

**Issue by nvinayvarma189** [skit-ai/dialogy-template-simple-transformers#43]
**Dialogy version**: 0.6.3

The setup instructions are outdated at a couple of sections

1. [Boilerplate section](https://github.com/Vernacular-ai/dialogy-template-simple-transformers#1-boilerplate): The interactive session which populates the `pyproject.toml` now only asks the `use_ner` question. The rest of the questions take some default values. 

The following screen is a result of executing `dialogy create hello-world dialogy-template-simple-transformers`

![image](https://user-images.githubusercontent.com/30727381/127141927-5133e1fe-6c30-4b93-a5dd-e7d5b4c6dcca.png)

2. [Installing Dependencies section](https://github.com/Vernacular-ai/dialogy-template-simple-transformers#2-install-dependencies): The first instruction `cd slu` should not be present as the following commands are to be executed from the root directory of the project

**Comment by ltbringer** [comment]
Solved in 0.1.5
